name: Build & deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: dist
        retention-days: 5
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout page repo
        uses: actions/checkout@v3
        with:
          repository: joonas175/joonas175.github.io
          ref: site
      - name: Clear previous
        run: rm -rf ./
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Add files to commit
        run: |
          git add --all
          git status
      - name: Create commit
        run: github commit -m "Updated page ${{ github.sha }}"
      - name: Upload to pages repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          branch: site
          github_token: ${{secrets.PAGE_REPO_ACCESS_KEY}}
          repository: joonas175/joonas175.github.io
